
[package]
edition.workspace = true
license.workspace = true
name = "agent9527-cloud-tasks-mock-client"
version.workspace = true

[lib]
name = "agent9527_cloud_tasks_mock_client"
path = "src/lib.rs"
test = false
doctest = false

[lints]
workspace = true

[dependencies]
chrono = { workspace = true }
agent9527-cloud-tasks-client = { workspace = true }
diffy = { workspace = true }
