// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Agent9527ErrorInfo } from "./Agent9527ErrorInfo";

export type TurnError = { message: string, agent9527ErrorInfo: Agent9527ErrorInfo | null, additionalDetails: string | null, };
