[package]
edition.workspace = true
license.workspace = true
name = "agent9527-extension-items"
version.workspace = true

[lib]
name = "agent9527_extension_items"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
agent9527-utils-absolute-path = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
ts-rs = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
