[package]
name = "agent9527-backend-client"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
http = { workspace = true }
url = { workspace = true }
agent9527-backend-openapi-models = { path = "../agent9527-backend-openapi-models" }
agent9527-api = { workspace = true }
agent9527-http-client = { workspace = true }
agent9527-login = { workspace = true }
agent9527-model-provider = { workspace = true }
agent9527-protocol = { workspace = true }

[dev-dependencies]
pretty_assertions = "1"
tokio = { workspace = true, features = ["macros", "rt"] }
wiremock = { workspace = true }
