[package]
name = "agent9527-linux-sandbox"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "agent9527-linux-sandbox"
path = "src/main.rs"

[lib]
name = "agent9527_linux_sandbox"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
clap = { workspace = true, features = ["derive"] }
agent9527-install-context = { workspace = true }
agent9527-network-proxy = { workspace = true }
agent9527-process-hardening = { workspace = true }
agent9527-protocol = { workspace = true }
agent9527-sandboxing = { workspace = true }
agent9527-utils-absolute-path = { workspace = true }
globset = { workspace = true }
landlock = { workspace = true }
libc = { workspace = true }
seccompiler = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
url = { workspace = true }

[target.'cfg(target_os = "linux")'.dev-dependencies]
agent9527-core = { workspace = true }
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = [
    "io-std",
    "macros",
    "process",
    "rt-multi-thread",
    "signal",
] }
