[package]
name = "agent9527-external-agent-migration"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
doctest = false
name = "agent9527_external_agent_migration"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
chrono = { workspace = true }
agent9527-analytics = { workspace = true }
agent9527-config = { workspace = true }
agent9527-core = { workspace = true }
agent9527-core-plugins = { workspace = true }
agent9527-hooks = { workspace = true }
agent9527-memories-write = { workspace = true }
agent9527-otel = { workspace = true }
agent9527-plugin = { workspace = true }
agent9527-protocol = { workspace = true }
agent9527-rollout = { workspace = true }
agent9527-utils-output-truncation = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
sha2 = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
agent9527-app-server-protocol = { workspace = true }
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
