[package]
edition.workspace = true
license.workspace = true
name = "agent9527-utils-output-truncation"
version.workspace = true

[lints]
workspace = true

[dependencies]
agent9527-protocol = { workspace = true }
agent9527-utils-string = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }

[lib]
doctest = false
