[package]
name = "agent9527-chatgpt"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
agent9527-connectors = { workspace = true }
agent9527-core = { workspace = true }
agent9527-git-utils = { workspace = true }
agent9527-login = { workspace = true }
agent9527-model-provider = { workspace = true }
agent9527-plugin = { workspace = true }
agent9527-utils-cli = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
agent9527-utils-cargo-bin = { workspace = true }
pretty_assertions = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }

[lib]
doctest = false
