[package]
edition.workspace = true
license.workspace = true
name = "agent9527-model-provider"
version.workspace = true

[lib]
doctest = false
name = "agent9527_model_provider"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
agent9527-api = { workspace = true }
agent9527-agent-identity = { workspace = true }
agent9527-aws-auth = { workspace = true }
agent9527-http-client = { workspace = true }
agent9527-feedback = { workspace = true }
agent9527-login = { workspace = true }
agent9527-model-provider-info = { workspace = true }
agent9527-models-manager = { workspace = true }
agent9527-otel = { workspace = true }
agent9527-protocol = { workspace = true }
agent9527-response-debug-context = { workspace = true }
http = { workspace = true }
tokio = { workspace = true, features = ["sync", "time"] }
tracing = { workspace = true, features = ["log"] }

[dev-dependencies]
pretty_assertions = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
wiremock = { workspace = true }
