[package]
edition.workspace = true
license.workspace = true
name = "agent9527-core-plugins"
version.workspace = true

[lib]
doctest = false
name = "agent9527_core_plugins"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
agent9527-analytics = { workspace = true }
agent9527-app-server-protocol = { workspace = true }
agent9527-config = { workspace = true }
agent9527-connectors = { workspace = true }
agent9527-core-skills = { workspace = true }
agent9527-exec-server = { workspace = true }
agent9527-git-utils = { workspace = true }
agent9527-hooks = { workspace = true }
agent9527-http-client = { workspace = true }
agent9527-login = { workspace = true }
agent9527-mcp = { workspace = true }
agent9527-model-provider = { workspace = true }
agent9527-otel = { workspace = true }
agent9527-plugin = { workspace = true }
agent9527-protocol = { workspace = true }
agent9527-skills = { workspace = true }
agent9527-shell-command = { workspace = true }
agent9527-tools = { workspace = true }
agent9527-utils-absolute-path = { workspace = true }
agent9527-utils-path = { workspace = true }
agent9527-utils-path-uri = { workspace = true }
agent9527-utils-plugins = { workspace = true }
chrono = { workspace = true }
dirs = { workspace = true }
flate2 = { workspace = true }
http = { workspace = true }
regex = { workspace = true }
semver = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
tar = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["fs", "macros", "rt", "time"] }
toml = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
zip = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
which = { workspace = true }

[dev-dependencies]
agent9527-exec-server-test-support = { workspace = true }
libc = { workspace = true }
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-test = { workspace = true, features = ["no-env-filter"] }
wiremock = { workspace = true }
