[package]
edition.workspace = true
license.workspace = true
name = "agent9527-memories-read"
version.workspace = true

[lib]
name = "agent9527_memories_read"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
agent9527-protocol = { workspace = true }
agent9527-shell-command = { workspace = true }
agent9527-utils-absolute-path = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
