[package]
edition.workspace = true
license.workspace = true
name = "agent9527-analytics"
version.workspace = true

[lib]
doctest = false
name = "agent9527_analytics"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
agent9527-app-server-protocol = { workspace = true }
agent9527-git-utils = { workspace = true }
agent9527-login = { workspace = true }
agent9527-model-provider = { workspace = true }
agent9527-plugin = { workspace = true }
agent9527-protocol = { workspace = true }
agent9527-state = { workspace = true }
os_info = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha1 = { workspace = true }
tokio = { workspace = true, features = [
    "macros",
    "rt-multi-thread",
] }
tracing = { workspace = true, features = ["log"] }

[dev-dependencies]
agent9527-utils-absolute-path = { workspace = true }
pretty_assertions = { workspace = true }
