[package]
edition.workspace = true
license.workspace = true
name = "agent9527-connectors-extension"
version.workspace = true

[lib]
name = "agent9527_connectors_extension"
path = "src/lib.rs"
doctest = false
test = false

[lints]
workspace = true

[dependencies]
agent9527-connectors = { workspace = true }
agent9527-core-plugins = { workspace = true }
agent9527-plugin = { workspace = true }
agent9527-utils-path-uri = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
