[package]
name = "agent9527-sandboxing"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "agent9527_sandboxing"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
agent9527-network-proxy = { workspace = true }
agent9527-protocol = { workspace = true }
agent9527-utils-absolute-path = { workspace = true }
agent9527-utils-path-uri = { workspace = true }
agent9527-windows-sandbox = { workspace = true }
dunce = { workspace = true }
libc = { workspace = true }
serde_json = { workspace = true }
regex-lite = { workspace = true }
tracing = { workspace = true, features = ["log"] }
url = { workspace = true }
which = { workspace = true }

[target.'cfg(windows)'.dependencies]
agent9527-utils-home-dir = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
