[package]
edition.workspace = true
license.workspace = true
name = "agent9527-core-api"
version.workspace = true

[lib]
doctest = false
name = "agent9527_core_api"
path = "src/lib.rs"
test = false

[lints]
workspace = true

[dependencies]
agent9527-app-server-protocol = { workspace = true }
agent9527-arg0 = { workspace = true }
agent9527-analytics = { workspace = true }
agent9527-config = { workspace = true }
agent9527-core = { workspace = true }
agent9527-extension-api = { workspace = true }
agent9527-home = { workspace = true }
agent9527-image-generation-extension = { workspace = true }
agent9527-exec-server = { workspace = true }
agent9527-features = { workspace = true }
agent9527-login = { workspace = true }
agent9527-model-provider-info = { workspace = true }
agent9527-models-manager = { workspace = true }
agent9527-protocol = { workspace = true }
agent9527-utils-absolute-path = { workspace = true }
