[package]
edition.workspace = true
license.workspace = true
name = "agent9527-core-skills"
version.workspace = true

[lib]
doctest = false
name = "agent9527_core_skills"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
agent9527-analytics = { workspace = true }
agent9527-config = { workspace = true }
agent9527-context-fragments = { workspace = true }
agent9527-exec-server = { workspace = true }
agent9527-login = { workspace = true }
agent9527-model-provider = { workspace = true }
agent9527-otel = { workspace = true }
agent9527-protocol = { workspace = true }
agent9527-shell-command = { workspace = true }
agent9527-skills = { workspace = true }
agent9527-utils-absolute-path = { workspace = true }
agent9527-utils-output-truncation = { workspace = true }
agent9527-utils-path-uri = { workspace = true }
agent9527-utils-plugins = { workspace = true }
dirs = { workspace = true }
dunce = { workspace = true }
futures = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
shlex = { workspace = true }
tokio = { workspace = true, features = ["fs", "macros", "rt"] }
toml = { workspace = true }
tracing = { workspace = true }
zip = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
