[package]
edition.workspace = true
license.workspace = true
name = "agent9527-extension-api"
version.workspace = true

[lib]
name = "agent9527_extension_api"
path = "src/lib.rs"
test = false
doctest = false

[lints]
workspace = true

[dependencies]
agent9527-config = { workspace = true }
agent9527-context-fragments = { workspace = true }
agent9527-exec-server-protocol = { workspace = true }
agent9527-protocol = { workspace = true }
agent9527-tools = { workspace = true }
agent9527-utils-absolute-path = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
