load("//:defs.bzl", "agent9527_rust_crate")

agent9527_rust_crate(
    name = "windows-sandbox-rs",
    binary_test_target_compatible_with = ["@platforms//os:windows"],
    build_script_data = [
        "agent9527-windows-sandbox-setup.manifest",
    ],
    crate_name = "agent9527_windows_sandbox",
    test_data_extra = [
        ":agent9527-command-runner",
        ":agent9527-windows-sandbox-setup",
    ],
)
