[package]
edition.workspace = true
license.workspace = true
name = "agent9527-models-manager"
version.workspace = true

[lib]
doctest = false
name = "agent9527_models_manager"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
chrono = { workspace = true, features = ["serde"] }
agent9527-collaboration-mode-templates = { workspace = true }
agent9527-http-client = { workspace = true }
agent9527-login = { workspace = true }
agent9527-otel = { workspace = true }
agent9527-protocol = { workspace = true }
agent9527-utils-output-truncation = { workspace = true }
agent9527-utils-template = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["fs", "sync", "time"] }
tracing = { workspace = true, features = ["log"] }

[dev-dependencies]
pretty_assertions = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
