[package]
name = "agent9527-utils-oss"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
agent9527-core = { workspace = true }
agent9527-lmstudio = { workspace = true }
agent9527-model-provider-info = { workspace = true }
agent9527-ollama = { workspace = true }

[lib]
doctest = false
